AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Node.js TypeScript API with GET, POST, and Scheduler

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    Environment:
      Variables:
        TABLE_NAME: !Ref ItemsTable
        NODE_OPTIONS: '--enable-source-maps'


Resources:
  # DynamoDB Table
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: items-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: birthdayMonthDay
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: BirthdayMonthDayIndex
          KeySchema:
            - AttributeName: birthdayMonthDay
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,DELETE,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  # GET Function
  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/handlers/
      Handler: getItems.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ItemsTable
      Events:
        GetItems:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user
            Method: GET
        GetItemById:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/{id}
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - ./src/handlers/getItems.ts
  
   # GET Function
  # GetBirthdayTodayFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: dist/handlers/
  #     Handler: getBirthdayToday.handler
  #     Policies:
  #       - DynamoDBReadPolicy:
  #           TableName: !Ref ItemsTable
  #     Events:
  #       GetBirthdayToday:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ApiGateway
  #           Path: /birthdaytoday
  #           Method: GET
  #   Metadata:
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: false
  #       Target: es2020
  #       Sourcemap: true
  #       EntryPoints:
  #         - ./src/handlers/getBirthdayToday.ts

  # POST Function
  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/handlers/
      Handler: createItem.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        CreateItem:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - ./src/handlers/createItem.ts

  # PUT Function
  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/handlers/
      Handler: putItem.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        PutItem:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user
            Method: PUT
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - ./src/handlers/putItem.ts

  # DELETE Function
  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/handlers/
      Handler: deleteItem.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        DeleteItem:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/{id}
            Method: DELETE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - ./src/handlers/deleteItem.ts

  # Scheduled Function (runs every 5 minutes)
  ScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/handlers/
      Handler: scheduled.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ItemsTable
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Name: BirthdayGreetingScheduler
            Enabled: true
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - ./src/handlers/scheduled.ts

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  ItemsTableName:
    Description: "DynamoDB table name"
    Value: !Ref ItemsTable
  BirthdayIndexName:
    Description: "Birthday GSI name"
    Value: "BirthdayMonthDayIndex"